theme: jekyll-theme-leap-day
title: '0xada4d'
description: check out my work, let me know what you think.
show_downloads: true

baseurl:

sidebar:
  twitter: true
  recent: true
  tags: true

# Google Analytics
google_analytics: UA-115179679-1