theme: jekyll-theme-leap-day
title: '0xada4d'
description: infosec n00b that loves to learn.<br>check out my work, let me know what you think.
show_downloads: true

baseurl:

sidebar:
  twitter: true
  recent: true
  tags: true
